
@host = http://0.0.0.0:39587

###
# test system health
GET {{host}}/api/v1/health HTTP/1.1

###
GET {{host}}/api/v1/agents HTTP/1.1

###
# spawn a coder agent
POST {{host}}/api/v1/agents
Content-Type: application/json

{
  "kind": "coder",
  "opts": {
    "system_prompt_identity": null,
    "system_prompt_section": null,
    "initial_message": [
      {
        "type": "text",
        "text": "say hi"
      }
    ]
  }
}
